# Generated by Django 5.1.2 on 2024-10-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('NW', 'News'), ('AR', 'Article')], default='article', max_length=2),
        ),
    ]
